Black Pixel V7
files-community/Custom-themes pull request #36
Opened 2021-08-04 20:08 UTC by erayrafet

* Themed buttons, lists, flyout submenus, scrollbars
* Improved design consistency
* Rounder borders

2021-08-05 20:47 UTC, yaichenbaum requested changes

2021-08-05 20:47 UTC, yaichenbaum commented on CustomThemesPackage/Black Pixel.xaml
>              <Color x:Key="SystemAccentColorLight3">#1A73E8</Color>
```suggestion
```

2021-08-06 05:56 UTC, erayrafet commented
![image](https://user-images.githubusercontent.com/34194191/128462843-9591e022-8e2b-4bc3-a4b4-a4ef1d9fea32.png)
![image](https://user-images.githubusercontent.com/34194191/128463027-0b1f587b-bdff-4979-97c1-b1f4f5de5061.png)
![image](https://user-images.githubusercontent.com/34194191/128463130-19eb5e6b-e592-4849-818c-df704975fdc2.png)

Maybe an issue with Windows 11, but the light theme accent colors are being used for input box underlines, progressbars, and pehaps more.

2021-08-20 12:30 UTC, yaichenbaum approved these changes
LGTM

2021-08-20 12:31 UTC, merged